// =============================================================================
// Inventory — 12 demonstration units.
//
// DEMO DATA. Prices, mileage, tax validity, ownership and service history are
// illustrative sample values for a portfolio build, not live stock (see
// /compliance). Performance figures are the manufacturers' published numbers,
// rounded; they are indicative and should be verified against the actual unit.
//
// Structure vs. text: hard facts (price, specs, image paths) live here; every
// human-readable string lives in i18n keyed by the bike `slug` under
// `bikes.<slug>.{tagline,description}` plus the shared `f.*` / `e.*` keys.
// When adding a unit: add the images (pnpm bikes), then the copy in BOTH
// i18n/locales/id.json and en.json, then run `pnpm i18n:check`.
//
// Photography: local, freely-licensed frames under /public/bikes produced by
// `pnpm bikes`; attribution ships on /credits (required by the CC licences).
// =============================================================================
import type { Bike } from '~/types'

const img = (slug: string, count: number): string[] =>
  Array.from({ length: count }, (_, i) => `/bikes/${slug}-${i + 1}.jpg`)

export const inventory: readonly Bike[] = [
  {
    slug: 'ducati-panigale-v4r',
    make: 'Ducati',
    model: 'Panigale V4 R',
    year: 2023,
    priceIdr: 1_250_000_000,
    condition: 'used',
    category: 'supersport',
    engineCc: 998,
    engineLayoutKey: 'spec.layout.v4',
    powerHp: 218,
    torqueNm: 111,
    weightKg: 193,
    mileageKm: 2_150,
    owners: 1,
    serviceHistory: 'full',
    taxValidUntil: '2027-03',
    colorKey: 'colors.rossoCorsa',
    electronicsKeys: ['e.imu', 'e.corneringAbs', 'e.tractionControl', 'e.wheelieControl', 'e.quickshifter', 'e.launchControl'],
    featureKeys: ['f.aeroWinglets', 'f.ohlinsSuspension', 'f.dryClutch', 'f.serviceBook'],
    images: img('ducati-panigale-v4r', 3),
    featured: true,
  },
  {
    slug: 'bmw-s1000rr',
    make: 'BMW Motorrad',
    model: 'S 1000 RR',
    year: 2024,
    priceIdr: 895_000_000,
    condition: 'new',
    category: 'supersport',
    engineCc: 999,
    engineLayoutKey: 'spec.layout.inline4',
    powerHp: 210,
    torqueNm: 113,
    weightKg: 197,
    mileageKm: 0,
    colorKey: 'colors.lightWhiteMsport',
    electronicsKeys: ['e.imu', 'e.corneringAbs', 'e.tractionControl', 'e.rideModes', 'e.quickshifter', 'e.hillHoldControl'],
    featureKeys: ['f.forgedWheels', 'f.tftDash', 'f.ledLighting', 'f.oemToolkit'],
    images: img('bmw-s1000rr', 3),
    featured: true,
  },
  {
    slug: 'honda-cbr1000rr-r-sp',
    make: 'Honda',
    model: 'CBR1000RR-R Fireblade SP',
    year: 2022,
    priceIdr: 785_000_000,
    condition: 'used',
    category: 'supersport',
    engineCc: 999,
    engineLayoutKey: 'spec.layout.inline4',
    powerHp: 214,
    torqueNm: 113,
    weightKg: 201,
    mileageKm: 6_300,
    owners: 1,
    serviceHistory: 'full',
    taxValidUntil: '2026-11',
    colorKey: 'colors.grandPrixTricolour',
    electronicsKeys: ['e.imu', 'e.corneringAbs', 'e.tractionControl', 'e.engineBrakeControl', 'e.quickshifter', 'e.rideModes'],
    featureKeys: ['f.ohlinsSuspension', 'f.brembo', 'f.aeroWinglets', 'f.serviceBook'],
    images: img('honda-cbr1000rr-r-sp', 3),
    featured: true,
  },
  {
    slug: 'yamaha-yzf-r1',
    make: 'Yamaha',
    model: 'YZF-R1',
    year: 2016,
    priceIdr: 425_000_000,
    condition: 'used',
    category: 'supersport',
    engineCc: 998,
    engineLayoutKey: 'spec.layout.crossplane4',
    powerHp: 200,
    torqueNm: 112,
    weightKg: 199,
    mileageKm: 18_400,
    owners: 2,
    serviceHistory: 'partial',
    taxValidUntil: '2026-08',
    colorKey: 'colors.teamYamahaBlue',
    electronicsKeys: ['e.imu', 'e.tractionControl', 'e.slideControl', 'e.launchControl', 'e.quickshifter'],
    featureKeys: ['f.magnesiumWheels', 'f.titaniumSilencer', 'f.tyresNew', 'f.frameSliders'],
    images: img('yamaha-yzf-r1', 2),
  },
  {
    slug: 'kawasaki-ninja-zx10r',
    make: 'Kawasaki',
    model: 'Ninja ZX-10R',
    year: 2021,
    priceIdr: 465_000_000,
    condition: 'used',
    category: 'supersport',
    engineCc: 998,
    engineLayoutKey: 'spec.layout.inline4',
    powerHp: 203,
    torqueNm: 115,
    weightKg: 207,
    mileageKm: 9_800,
    owners: 1,
    serviceHistory: 'full',
    taxValidUntil: '2027-01',
    colorKey: 'colors.limeGreenEbony',
    electronicsKeys: ['e.imu', 'e.corneringAbs', 'e.tractionControl', 'e.launchControl', 'e.quickshifter', 'e.cruiseControl'],
    featureKeys: ['f.brembo', 'f.tftDash', 'f.paddockStand', 'f.serviceBook'],
    images: img('kawasaki-ninja-zx10r', 3),
  },
  {
    slug: 'aprilia-rsv4-rr',
    make: 'Aprilia',
    model: 'RSV4 RR',
    year: 2019,
    priceIdr: 585_000_000,
    condition: 'used',
    category: 'supersport',
    engineCc: 999,
    engineLayoutKey: 'spec.layout.v4',
    powerHp: 201,
    torqueNm: 115,
    weightKg: 204,
    mileageKm: 21_500,
    owners: 2,
    serviceHistory: 'partial',
    taxValidUntil: '2026-06',
    colorKey: 'colors.nardoMatt',
    electronicsKeys: ['e.imu', 'e.corneringAbs', 'e.tractionControl', 'e.wheelieControl', 'e.launchControl', 'e.quickshifter'],
    featureKeys: ['f.akrapovicExhaust', 'f.ohlinsSuspension', 'f.frameSliders', 'f.tyresNew'],
    images: img('aprilia-rsv4-rr', 3),
  },
  {
    slug: 'ktm-1290-super-duke-r',
    make: 'KTM',
    model: '1290 Super Duke R',
    year: 2021,
    priceIdr: 495_000_000,
    condition: 'used',
    category: 'naked',
    engineCc: 1301,
    engineLayoutKey: 'spec.layout.vTwin',
    powerHp: 180,
    torqueNm: 140,
    weightKg: 200,
    mileageKm: 14_700,
    owners: 1,
    serviceHistory: 'full',
    taxValidUntil: '2026-12',
    colorKey: 'colors.orangeWhite',
    electronicsKeys: ['e.imu', 'e.corneringAbs', 'e.tractionControl', 'e.rideModes', 'e.quickshifter', 'e.cruiseControl'],
    featureKeys: ['f.wpSuspension', 'f.brembo', 'f.tailTidy', 'f.serviceBook'],
    images: img('ktm-1290-super-duke-r', 3),
    featured: true,
  },
  {
    slug: 'yamaha-mt09',
    make: 'Yamaha',
    model: 'MT-09',
    year: 2024,
    priceIdr: 295_000_000,
    condition: 'new',
    category: 'naked',
    engineCc: 890,
    engineLayoutKey: 'spec.layout.triple',
    powerHp: 117,
    torqueNm: 93,
    weightKg: 193,
    mileageKm: 0,
    colorKey: 'colors.cyanStorm',
    electronicsKeys: ['e.imu', 'e.corneringAbs', 'e.tractionControl', 'e.rideModes', 'e.quickshifter', 'e.cruiseControl'],
    featureKeys: ['f.tftDash', 'f.ledLighting', 'f.spinForgedWheels', 'f.oemToolkit'],
    images: img('yamaha-mt09', 2),
  },
  {
    slug: 'mv-agusta-brutale-1000-rs',
    make: 'MV Agusta',
    model: 'Brutale 1000 RS',
    year: 2024,
    priceIdr: 1_050_000_000,
    condition: 'new',
    category: 'naked',
    engineCc: 998,
    engineLayoutKey: 'spec.layout.inline4',
    powerHp: 208,
    torqueNm: 116,
    weightKg: 205,
    mileageKm: 0,
    colorKey: 'colors.rossoAgo',
    electronicsKeys: ['e.imu', 'e.corneringAbs', 'e.tractionControl', 'e.rideModes', 'e.quickshifter', 'e.cruiseControl'],
    featureKeys: ['f.marzocchiSuspension', 'f.brembo', 'f.tftDash', 'f.oemToolkit'],
    images: img('mv-agusta-brutale-1000-rs', 3),
    featured: true,
  },
  {
    slug: 'triumph-street-triple-r',
    make: 'Triumph',
    model: 'Street Triple R 675',
    year: 2013,
    priceIdr: 165_000_000,
    condition: 'used',
    category: 'naked',
    engineCc: 675,
    engineLayoutKey: 'spec.layout.triple',
    powerHp: 105,
    torqueNm: 68,
    weightKg: 183,
    mileageKm: 42_800,
    owners: 3,
    serviceHistory: 'partial',
    taxValidUntil: '2026-05',
    colorKey: 'colors.phantomBlack',
    electronicsKeys: ['e.abs', 'e.slipperClutch'],
    featureKeys: ['f.arrowExhaust', 'f.tailTidy', 'f.tyresNew', 'f.frameSliders'],
    images: img('triumph-street-triple-r', 3),
  },
  {
    slug: 'kawasaki-z900rs',
    make: 'Kawasaki',
    model: 'Z900RS',
    year: 2023,
    priceIdr: 385_000_000,
    condition: 'used',
    category: 'heritage',
    engineCc: 948,
    engineLayoutKey: 'spec.layout.inline4',
    powerHp: 111,
    torqueNm: 98,
    weightKg: 215,
    mileageKm: 7_900,
    owners: 1,
    serviceHistory: 'full',
    taxValidUntil: '2027-02',
    colorKey: 'colors.candytoneOrange',
    electronicsKeys: ['e.abs', 'e.tractionControl', 'e.rideModes', 'e.slipperClutch'],
    featureKeys: ['f.originalPaint', 'f.ledLighting', 'f.serviceBook', 'f.singleOwner'],
    images: img('kawasaki-z900rs', 3),
  },
  {
    slug: 'ducati-multistrada-v4s',
    make: 'Ducati',
    model: 'Multistrada V4 S',
    year: 2025,
    priceIdr: 1_095_000_000,
    condition: 'new',
    category: 'sport-touring',
    engineCc: 1158,
    engineLayoutKey: 'spec.layout.v4',
    powerHp: 170,
    torqueNm: 124,
    weightKg: 240,
    mileageKm: 0,
    colorKey: 'colors.auroraBlack',
    electronicsKeys: ['e.imu', 'e.corneringAbs', 'e.tractionControl', 'e.semiActiveSuspension', 'e.radarAcc', 'e.cruiseControl'],
    featureKeys: ['f.touringScreen', 'f.heatedGrips', 'f.panniersReady', 'f.tftDash'],
    images: img('ducati-multistrada-v4s', 2),
  },
]

/** Fast slug lookup for detail pages and the compare tray. */
export const inventoryBySlug: Readonly<Record<string, Bike>> = Object.fromEntries(
  inventory.map((bike) => [bike.slug, bike]),
)
